In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("my_data2.csv")
dataset.head()


Animal   Age    Worth Friendly
0    Cat   4.0  72000.0       No
1    Dog  17.0  48000.0      Yes
2  Moose   6.0  54000.0       No
3    Dog   8.0  61000.0       No
4  Moose   4.0      NaN      Yes

In [4]:
X = dataset.iloc[:,:-1].values
X.shape

(1005, 3)

In [5]:
y = dataset.iloc[:,3].values
y

array(['No', 'Yes', 'No', ..., 'Yes', 'No', 'Yes'], dtype=object)

In [8]:
from sklearn.preprocessing import Imputer 
imputer = Imputer(missing_values = np.nan, strategy = "mean", axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X[:,1:3]

c:\users\rade\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[4.0, 72000.0],
       [17.0, 48000.0],
       [6.0, 54000.0],
       ...,
       [15.0, 58000.0],
       [9.037919826652221, 52000.0],
       [12.0, 79000.0]], dtype=object)

In [76]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([0, 1, 2, ..., 0, 1, 0], dtype=object)

In [77]:
from sklearn.preprocessing import OneHotEncoder 
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

c:\users\rade\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([0, 1, 0, ..., 1, 0, 1])

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [79]:
X_train.shape

(804, 5)

In [80]:
from sklearn.svm import SVC
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train,y_train)
y_pred = svclassifier.predict(X_test)

In [84]:
num_correct = np.sum(y_pred == y_test) 
accuracy = float(num_correct)/y_pred.shape[0]
(accuracy * 100)

66.16915422885572

In [87]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[35 68]
 [ 0 98]]
              precision    recall  f1-score   support

           0       1.00      0.34      0.51       103
           1       0.59      1.00      0.74        98

   micro avg       0.66      0.66      0.66       201
   macro avg       0.80      0.67      0.62       201
weighted avg       0.80      0.66      0.62       201



In [88]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

66.16915422885572